version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-estik
    environment:
      POSTGRES_DB: estik-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-estik
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - pgadmindata:/var/lib/pgadmin

  app-api:
    build: .
    container_name: spring-estik-api
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}

  postgres-backup:
    build:
      context: ./backup
    container_name: postgres-estik-backup
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      PGHOST: postgres-db
      PGPORT: 5432
      PGDATABASE: estik-db
      PGUSER: ${DB_USERNAME}
      PGPASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    volumes:
      - ./backups:/backups
    restart: unless-stopped

volumes:
  pgdata:
  pgadmindata: