spring.application.name=estik

spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=postgres
spring.datasource.password=postgres

api.security.secret=${SECRET_KEY:minha-chave-secreta-super-segura-com-mais-de-32-caracteres!}

spring.datasource.driver-class-name=org.postgresql.Driver

# Força o dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true